modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="mapfrontiers"
version="${version}"
displayName="MapFrontiers"
updateJSONURL="https://alejandrocoria.games/projects/MapFrontiers/update.json"
displayURL="https://alejandrocoria.games/projects/MapFrontiers/"
logoFile="logo.png"
credits="By Alejandro Coria. Many thanks to the JourneyMap team."
authors="Alejandro Coria (MemeSapiens)"
description='''
This mod is an addon for Journey Map that allows you to divide the map into regions and assign them names and colors.
'''

[[dependencies.mapfrontiers]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mapfrontiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mapfrontiers]]
    modId="journeymap"
    mandatory=true
    versionRange="[1.19-5.8,)"
    ordering="NONE"
    side="BOTH"
